# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-19 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190318_0545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('creator', 'course_name', 'session_name')]),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set([('course', 'student'), ('course', 'class_id')]),
        ),
    ]
