# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-03-19 00:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_auto_20190319_0633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=256)),
                ('topic_description', models.TextField(blank=True, null=True)),
                ('topic_serial', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_deleted', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_creator', to=settings.AUTH_USER_MODEL)),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('course', 'topic_serial'), ('course', 'topic_name')]),
        ),
    ]
